package structural.facade;

public enum Authority {
    ACCESS_SIMPLE_USER_DASHBORD,
    ACCESS_ADMIN_DASHBOARD,
    ACCES_SUPER_ADMIN_DASHBOARD,
    MODIFY_SIMPLE_USER_PROFIL,
    READ_SIMPLE_USER_PROFIL,
    READ_ADMIN_HISTORY,
    GRANT_AUTHORITY,
    REVOKE_AUTHORITY;
}
