package structural.decorator;

public enum Skill {
    JAVASCRIPT_DEVELOPER,
    JAVA_DEVELOPER,
    PYTHON_DEVELOPER,
    PROJECT_MANAGEMENT,
    DATA_SCIENCE,
    DATA_ANALYSIS,
    PROBLEM_SOLVING,
    DATA_STRUCTURES,
    DESIGN;

}
